///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String animDoneAnime = 'assets/anim/done_anime.json';
  static const String animEmptyDataLottie =
      'assets/anim/empty-data-lottie.json';
  static const String animInviteFriendsLottie =
      'assets/anim/invite-friends-lottie.json';
  static const String animLocation = 'assets/anim/location.json';
  static const String gifsDataVerification =
      'assets/gifs/data-verification.gif';
  static const String gifsHospital = 'assets/gifs/hospital.gif';
  static const String gifsNoUser = 'assets/gifs/no_user.gif';
  static const String gifsOtp = 'assets/gifs/otp.gif';
  static const String gifsWelcomePerson = 'assets/gifs/welcome_person.gif';
  static const String iconsActivity = 'assets/icons/activity.svg';
  static const String iconsAd = 'assets/icons/ad.svg';
  static const String iconsAd2 = 'assets/icons/ad-2.svg';
  static const String iconsArrowDown = 'assets/icons/arrow_down.svg';
  static const String iconsArrowRightDown = 'assets/icons/arrow-right-down.svg';
  static const String iconsArrowRightUp = 'assets/icons/arrow-right-up.svg';
  static const String iconsArrowsShuffle = 'assets/icons/arrows-shuffle.svg';
  static const String iconsBell = 'assets/icons/bell.svg';
  static const String iconsBookingFirstCome =
      'assets/icons/booking_first_come.svg';
  static const String iconsBuildingHospital =
      'assets/icons/building-hospital.svg';
  static const String iconsBuildingSkyscraper =
      'assets/icons/building-skyscraper.svg';
  static const String iconsBuildingWarehouse =
      'assets/icons/building-warehouse.svg';
  static const String iconsCalculator = 'assets/icons/calculator.svg';
  static const String iconsCalendar = 'assets/icons/calendar.svg';
  static const String iconsCalendarActive = 'assets/icons/calendar-active.svg';
  static const String iconsCalendarEvent = 'assets/icons/calendar-event.svg';
  static const String iconsCalendarOff = 'assets/icons/calendar-off.svg';
  static const String iconsCalendarPlus = 'assets/icons/calendar-plus.svg';
  static const String iconsCalendarPrefix = 'assets/icons/calendar_prefix.svg';
  static const String iconsCalendarTime = 'assets/icons/calendar-time.svg';
  static const String iconsCall = 'assets/icons/call.svg';
  static const String iconsCamera = 'assets/icons/camera.svg';
  static const String iconsCameraPlus = 'assets/icons/camera-plus.svg';
  static const String iconsCash = 'assets/icons/cash.svg';
  static const String iconsCashBack = 'assets/icons/cash_back.svg';
  static const String iconsCashBanknote = 'assets/icons/cash-banknote.svg';
  static const String iconsCashBanknoteOff =
      'assets/icons/cash-banknote-off.svg';
  static const String iconsCheck = 'assets/icons/check.svg';
  static const String iconsCheckupList = 'assets/icons/checkup-list.svg';
  static const String iconsChevronLeft = 'assets/icons/chevron-left.svg';
  static const String iconsChevronRight = 'assets/icons/chevron-right.svg';
  static const String iconsChild = 'assets/icons/child.svg';
  static const String iconsCleanClinic = 'assets/icons/clean_clinic.svg';
  static const String iconsClinicFacilities =
      'assets/icons/clinic_facilities.svg';
  static const String iconsClinicLocation = 'assets/icons/clinic_location.svg';
  static const String iconsClockOrange = 'assets/icons/clock_orange.svg';
  static const String iconsCopy = 'assets/icons/copy.svg';
  static const String iconsCreditCard = 'assets/icons/credit-card.svg';
  static const String iconsDiagnosis = 'assets/icons/diagnosis.svg';
  static const String iconsDoctor = 'assets/icons/doctor.svg';
  static const String iconsDoctorCard = 'assets/icons/doctor-card.svg';
  static const String iconsDoctorSheet = 'assets/icons/doctor_sheet.svg';
  static const String iconsDoneRequest = 'assets/icons/done_request.svg';
  static const String iconsDotsVertical = 'assets/icons/dots-vertical.svg';
  static const String iconsEdit = 'assets/icons/edit.svg';
  static const String iconsEgyFlag = 'assets/icons/egyFlag.svg';
  static const String iconsEye = 'assets/icons/eye.svg';
  static const String iconsFacebook = 'assets/icons/facebook.svg';
  static const String iconsFemale = 'assets/icons/female.svg';
  static const String iconsFileUpload = 'assets/icons/file-upload.svg';
  static const String iconsFilter = 'assets/icons/filter.svg';
  static const String iconsFlag = 'assets/icons/flag.svg';
  static const String iconsFrame = 'assets/icons/frame.svg';
  static const String iconsFrame4 = 'assets/icons/frame4.svg';
  static const String iconsFullStar = 'assets/icons/full_star.svg';
  static const String iconsGoodListener = 'assets/icons/good_listener.svg';
  static const String iconsGoogle = 'assets/icons/Google.svg';
  static const String iconsHalf = 'assets/icons/half.svg';
  static const String iconsHalfStar = 'assets/icons/half_star.svg';
  static const String iconsHalfStar1 = 'assets/icons/half_star1.svg';
  static const String iconsHeart = 'assets/icons/heart.svg';
  static const String iconsHome = 'assets/icons/home.svg';
  static const String iconsHomeActive = 'assets/icons/home-active.svg';
  static const String iconsHospital = 'assets/icons/hospital.svg';
  static const String iconsHospitalSheet = 'assets/icons/hospital_sheet.svg';
  static const String iconsLanguage = 'assets/icons/language.svg';
  static const String iconsLatest = 'assets/icons/latest.svg';
  static const String iconsLicenceDocument =
      'assets/icons/licence-document.svg';
  static const String iconsLicense = 'assets/icons/license.svg';
  static const String iconsLine = 'assets/icons/line.svg';
  static const String iconsLink = 'assets/icons/link.svg';
  static const String iconsLock = 'assets/icons/lock.svg';
  static const String iconsLogoWithoutText =
      'assets/icons/Logo-without-text.png';
  static const String iconsLogout = 'assets/icons/logout.svg';
  static const String iconsMail = 'assets/icons/Mail.svg';
  static const String iconsMale = 'assets/icons/male.svg';
  static const String iconsMap = 'assets/icons/map.svg';
  static const String iconsMap2 = 'assets/icons/map-2.svg';
  static const String iconsMedications = 'assets/icons/medications.svg';
  static const String iconsMedicine = 'assets/icons/medicine.svg';
  static const String iconsMessage = 'assets/icons/message.svg';
  static const String iconsMyAccount = 'assets/icons/my-account.svg';
  static const String iconsMyAccountActive =
      'assets/icons/my-account-active.svg';
  static const String iconsMyBooking = 'assets/icons/my-booking.svg';
  static const String iconsMyBookingActive =
      'assets/icons/my-booking-active.svg';
  static const String iconsMyCalender = 'assets/icons/my_calender.svg';
  static const String iconsNationalId = 'assets/icons/national-id.svg';
  static const String iconsNetworkError = 'assets/icons/network_error.svg';
  static const String iconsNoResults = 'assets/icons/no-results.svg';
  static const String iconsNotFound = 'assets/icons/not_found.svg';
  static const String iconsNotifications = 'assets/icons/notifications.svg';
  static const String iconsNotificationsActive =
      'assets/icons/notifications-active.svg';
  static const String iconsOnHome = 'assets/icons/on_home.svg';
  static const String iconsPhone = 'assets/icons/phone.svg';
  static const String iconsPlus = 'assets/icons/plus.svg';
  static const String iconsPointsArrow = 'assets/icons/points_arrow.svg';
  static const String iconsProfile = 'assets/icons/profile.svg';
  static const String iconsProfileActive = 'assets/icons/profile-active.svg';
  static const String iconsQrCodeScan = 'assets/icons/qr-code-scan.svg';
  static const String iconsQrcode = 'assets/icons/qrcode.svg';
  static const String iconsRegion = 'assets/icons/region.svg';
  static const String iconsRemove = 'assets/icons/remove.svg';
  static const String iconsRepeat = 'assets/icons/repeat.svg';
  static const String iconsReportAnalytics =
      'assets/icons/report-analytics.svg';
  static const String iconsReview = 'assets/icons/review.svg';
  static const String iconsSaudi = 'assets/icons/saudi.svg';
  static const String iconsSearchForIcon = 'assets/icons/search_for_icon.svg';
  static const String iconsSettings = 'assets/icons/settings.svg';
  static const String iconsStar = 'assets/icons/star.svg';
  static const String iconsStars = 'assets/icons/stars.svg';
  static const String iconsStethoscope = 'assets/icons/stethoscope.svg';
  static const String iconsSurveyTrick = 'assets/icons/survey-trick.svg';
  static const String iconsTime = 'assets/icons/time.svg';
  static const String iconsTool = 'assets/icons/tool.svg';
  static const String iconsTrash = 'assets/icons/trash.svg';
  static const String iconsUser = 'assets/icons/user.svg';
  static const String iconsUserPlus = 'assets/icons/user-plus.svg';
  static const String iconsVideo = 'assets/icons/video.svg';
  static const String iconsWaitingTime = 'assets/icons/waiting_time.svg';
  static const String iconsWaitingTimeIcon =
      'assets/icons/waiting_time_icon.svg';
  static const String iconsWallet = 'assets/icons/wallet.svg';
  static const String iconsWhats = 'assets/icons/whats.svg';
  static const String iconsX = 'assets/icons/x.svg';
  static const String imagesCheck = 'assets/images/check.png';
  static const String imagesClose = 'assets/images/close.png';
  static const String imagesDone = 'assets/images/done.png';
  static const String imagesEmail = 'assets/images/email.png';
  static const String imagesGallery = 'assets/images/gallery.png';
  static const String imagesHospitalPlaceholder =
      'assets/images/hospital-placeholder.png';
  static const String imagesLightMode = 'assets/images/light-mode.png';
  static const String imagesLogoAr = 'assets/images/logo.png';
  static const String imagesLogoEn = 'assets/images/logo.png';
  static const String imagesNightMode = 'assets/images/night-mode.png';
  static const String imagesNoData = 'assets/images/noData.png';
  static const String imagesSuccessAlert = 'assets/images/successAlert.png';
  static const String imagesUser = 'assets/images/user.png';
  static const String imagesUserProfile = 'assets/images/user_profile.png';
  static const String imagesWarning = 'assets/images/warning.png';
  static const String laundry = 'assets/images/laundry.png';
  static const String laundryh = 'assets/images/laundryh.png';
  static const String appbarBackground = 'assets/images/appbar_background.png';
  static const String orderCompleted = 'assets/images/order_completed.png';
  static const String langAr = 'lang/ar.json';
  static const String langEn = 'lang/en.json';
  static const String uRWDINArabicURWDINArabicBlack =
      'assets/fonts/URW-DIN-Arabic/URW-DIN-Arabic-Black.ttf';
  static const String uRWDINArabicURWDINArabicBold =
      'assets/fonts/URW-DIN-Arabic/URW-DIN-Arabic-Bold.ttf';
  static const String uRWDINArabicURWDINArabicLight =
      'assets/fonts/URW-DIN-Arabic/URW-DIN-Arabic-Light.ttf';
  static const String uRWDINArabicURWDINArabicMedium =
      'assets/fonts/URW-DIN-Arabic/URW-DIN-Arabic-Medium.ttf';
  static const String uRWDINArabicURWDINArabicRegular =
      'assets/fonts/URW-DIN-Arabic/URW-DIN-Arabic-Regular.ttf';
  static const String uRWDINArabicURWDINArabicSemiBold =
      'assets/fonts/URW-DIN-Arabic/URW-DIN-Arabic-SemiBold.ttf';
  static const String uRWDINArabicURWDINArabicThin =
      'assets/fonts/URW-DIN-Arabic/URW-DIN-Arabic-Thin.ttf';
  static const String uRWDINArabicURWDINArabicXLight =
      'assets/fonts/URW-DIN-Arabic/URW-DIN-Arabic-XLight.ttf';
  //Amr-----------------------------------------
  static const String sudiaFlagImage = 'assets/images/El_Sudia.png';
  static const String usaFlagImage = 'assets/images/Usa_Flag.png';
  static const String kindUserBackGroundImage =
      'assets/images/kind_user_background.png';
  static const String userImage = 'assets/images/user_logo_image.png';
  static const String doctorImage = 'assets/images/doctor_logo_image.png';
  static const String loginLogoImage = 'assets/images/login_logo_image.png';
  static const String loginBorderImage = 'assets/images/login_border_image.png';
  static const String otpEditPenSvg = 'assets/icons/otp_edit_pen.svg';
  static const String newPasswordLogoImage =
      'assets/images/new_passwod_logo_image.png';
  static const String otpLogoBackgroundImage =
      'assets/images/otp_logo_background.png';
  static const String reactiveLogoImage =
      'assets/images/reactive_logo_image.png';
  static const String successChangePassBackgroundImage =
      'assets/images/success_change_pass_background_image.png';
  static const String successChangePassLogoImage =
      'assets/images/success_change_pass_logo_image.png';
  static const String onBoardingOneImage = 'assets/images/onBoarding_1.png';
  static const String onBoardingTwoImage = 'assets/images/onBoarding_2.png';
  static const String onBoardingThreeImage = 'assets/images/onBoarding_3.png';
  static const String onBoardingOneBackGroundImage =
      'assets/images/onBoarding_backGround.png';
  static const String onBoardingButtonSvg =
      'assets/icons/onBoarding_button.svg';

  static const String orders = 'assets/images/orders.png';

  static const String services = 'assets/images/services.png';

  static const String profilePenEditeImage =
      'assets/images/profile_pen_edit.png';
  static const String infoIconSvg = 'assets/icons/info_icon.svg';
  static const String notificationIconSvg =
      'assets/icons/notification_icon.svg';
  static const String orderIconSvg = 'assets/icons/orders_icon.svg';
  static const String orderIconNavBarSvg = 'assets/icons/orders_icon_1.svg';
  static const String phoneIconSvg = 'assets/icons/phone_icon.svg';
  static const String settingIconSvg = 'assets/icons/setting_icon.svg';
  static const String aboutAppIconSvg = 'assets/icons/info_setting_icon.svg';
  static const String tearmsAndCondationsIconSvg =
      'assets/icons/tearms_icon.svg';
  static const String publicQuationIconSvg =
      'assets/icons/public_quation_icon.svg';
  static const String rateIconSvg = 'assets/icons/rate_icon.svg';
  static const String langIconSvg = 'assets/icons/language_icon.svg';
  static const String changeModeIconSvg = 'assets/icons/change_mode_icon.svg';
  static const String logOutIconSvg = 'assets/icons/logout_icon.svg';
  static const String aboutUsImage = 'assets/images/about_us_image.png';
  static const String facebookIconImage =
      'assets/images/facebook_icon_image.png';
  static const String instegramIconImage =
      'assets/images/instegram_icon_image.png';
  static const String helperImage = 'assets/images/helper_image.png';
  static const String snapchatIconImage =
      'assets/images/snapchat_icon_image.png';
  static const String tearmsAndCondationImage =
      'assets/images/tearms_and_condation_image.png';
  static const String twitterIconImage = 'assets/images/twitter_icon_image.png';
  static const String contactUsImage = 'assets/images/contact_us_image.png';
  static const String mailIconSvg = 'assets/icons/mail_icon.svg';
  static const String whatsIconSvg = 'assets/icons/whats_icon.svg';
  static const String personIconSvg = 'assets/icons/person_icon.svg';
  static const String atIconSvg = 'assets/icons/at_icon.svg';
  static const String saveIconSvg = 'assets/icons/save_icon.svg';
  static const String messageIconSvg = 'assets/icons/message_icon.svg';
  static const String messageIconNavBarSvg = 'assets/icons/message_icon_1.svg';
  static const String tearmsAndCondationTitelSvg =
      'assets/icons/tearms_titel_icon.svg';
  static const String notificationLogoItemImage =
      'assets/images/notification_image.png';
  static const String menuLogoSvg = 'assets/icons/menu_icon.svg';
  static const String notFoundNotificationImage =
      'assets/images/not_found_notification_image.png';




  ///ezzat
  static const String locationIconSvg = 'assets/icons/location_icon.svg';


  static const String changeEmail = 'assets/images/change_email.png';

  static const String personImage = 'assets/images/person.png';
  static const String imagesMyFileIcon = 'assets/images/myFileIcon.png';
  static const String todoListImage = 'assets/images/todo_list.png';
  static const String visitsNeededImage = 'assets/images/visits_needed_image.png';
  static const String patientBillsImage = 'assets/images/patient_bills.png';
  static const String patientFilesImage = 'assets/images/patient_files.png';
  static const String iconVisitCodeSvg = 'assets/icons/iconVisitCode.svg';
  static const String iconDateSvg = 'assets/icons/iconDateSvg.svg';
  static const String iconClockSvg = 'assets/icons/iconClock.svg';
  static const String iconLocationSvg = 'assets/icons/iconLocation.svg';
  static const String iconWaitingSvg = 'assets/icons/iconWaiting.svg';
  static const String iconPhoneSvg = 'assets/icons/iconPhone.svg';
  static const String personImages = 'assets/images/person2.png';

  //Amr Assets -----------------------
  static const String onBoardingImage = 'assets/images/onboarding_image.png';
  static const String mapBackgroundImage = 'assets/images/map_backGround.png';
  static const String selectImageProfileImage =
      'assets/images/select_image_profile.png';
  static const String emailIconSvg = 'assets/icons/email_icon.svg';
  static const String passIconSvg = 'assets/icons/password_icon.svg';
  static const String passEyeIconSvg = 'assets/icons/password_icon.svg';



///bill
  static const String pharmacyStore = 'assets/icons/pharmacy-store.svg';
  static const String filterIcon = 'assets/icons/filter-icon.svg';

}
